// <auto-generated />
using System;
using CaseStage.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseStage.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseStage.Application.Areas.Models.AreaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProccessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProccessId");

                    b.ToTable("FileModel");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Documentation")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int?>("IdParent")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Proccess");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ProccessId")
                        .HasColumnType("int");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProccessId");

                    b.ToTable("ProccessPerson");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessSystem", b =>
                {
                    b.Property<int>("ProccessId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasIndex("SystemId");

                    b.ToTable("ProccessSystem");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.SystemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasMaxLength(800)
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("System");
                });

            modelBuilder.Entity("PersonModelProccessModel", b =>
                {
                    b.Property<int>("PersonsId")
                        .HasColumnType("int");

                    b.Property<int>("ProccessId")
                        .HasColumnType("int");

                    b.HasKey("PersonsId", "ProccessId");

                    b.HasIndex("ProccessId");

                    b.ToTable("PersonModelProccessModel");
                });

            modelBuilder.Entity("ProccessModelSystemModel", b =>
                {
                    b.Property<int>("ProccessId")
                        .HasColumnType("int");

                    b.Property<int>("SystemsId")
                        .HasColumnType("int");

                    b.HasKey("ProccessId", "SystemsId");

                    b.HasIndex("SystemsId");

                    b.ToTable("ProccessModelSystemModel");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.FileModel", b =>
                {
                    b.HasOne("CaseStage.Application.Areas.Models.ProccessModel", "Proccess")
                        .WithMany("File")
                        .HasForeignKey("ProccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proccess");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessModel", b =>
                {
                    b.HasOne("CaseStage.Application.Areas.Models.AreaModel", "Area")
                        .WithMany("Proccess")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessPerson", b =>
                {
                    b.HasOne("CaseStage.Application.Areas.Models.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseStage.Application.Areas.Models.ProccessModel", "Proccess")
                        .WithMany()
                        .HasForeignKey("ProccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Proccess");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessSystem", b =>
                {
                    b.HasOne("CaseStage.Application.Areas.Models.SystemModel", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("PersonModelProccessModel", b =>
                {
                    b.HasOne("CaseStage.Application.Areas.Models.PersonModel", null)
                        .WithMany()
                        .HasForeignKey("PersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseStage.Application.Areas.Models.ProccessModel", null)
                        .WithMany()
                        .HasForeignKey("ProccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProccessModelSystemModel", b =>
                {
                    b.HasOne("CaseStage.Application.Areas.Models.ProccessModel", null)
                        .WithMany()
                        .HasForeignKey("ProccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseStage.Application.Areas.Models.SystemModel", null)
                        .WithMany()
                        .HasForeignKey("SystemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.AreaModel", b =>
                {
                    b.Navigation("Proccess");
                });

            modelBuilder.Entity("CaseStage.Application.Areas.Models.ProccessModel", b =>
                {
                    b.Navigation("File");
                });
#pragma warning restore 612, 618
        }
    }
}
